#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*           Use the multi-arch images at             *
*                                                    *
*               linuxserver/pydio                    *
*                                                    *
*    https://hub.docker.com/r/linuxserver/pydio      *
*                                                    *
*   https://github.com/linuxserver/docker-pydio      *
*                                                    *
*                                                    *
*                                                    *
******************************************************'
